name: e_commerce
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'







dependencies:
  get:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.6
  velocity_x:
  permission_handler: ^11.3.1
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  firebase_storage: ^11.7.4
  cloud_firestore: ^4.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^3.0.0





flutter:

  
  
  
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/fonts/



  fonts:
    - family: sans_regular
      fonts:
        - asset: assets/fonts/sans_regular.ttf

    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf



  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
